insert into Products (ctgy_id, name, dsc, price) Values (1, 'TV', 'It belongs to electronics', 999.99);
insert into Products (ctgy_id, name, dsc, price) Values (1, 'iPhone', 'It belongs to electronics', 1099.99);
insert into Products (ctgy_id, name, dsc, price) Values (1, 'Desktop', 'It belongs to electronics', 699.99);
insert into Products (ctgy_id, name, dsc, price) Values (2, 'The Fairy Tale', 'It belongs to books', 19.99);
insert into Products (ctgy_id, name, dsc, price) Values (2, 'The Atomic Habits', 'It belongs to books', 11.99);
insert into Products (ctgy_id, name, dsc, price) Values (3, 'Tylenol', 'It belongs to Health and Beauty', 25.99);
insert into Products (ctgy_id, name, dsc, price) Values (3, 'Shower Gel', 'It belongs to Health and Beauty', 9.99);
insert into Products (ctgy_id, name, dsc, price) Values (3, 'Shampoo', 'It belongs to Health and Beauty', 12.99);
insert into Products (ctgy_id, name, dsc, price) Values (4, 'BBQ', 'It belongs to Home and Kitchen', 229.99);
insert into Products (ctgy_id, name, dsc, price) Values (4, 'Oven', 'It belongs to Home and Kitchen', 1299.99);
insert into Products (ctgy_id, name, dsc, price) Values (5, 'Hoodie', 'It belongs to Clothing', 29.99);
insert into Products (ctgy_id, name, dsc, price) Values (5, 'Winter Jacket', 'It belongs to Clothing', 119.99);
